import Database from "better-sqlite3";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const db = new Database(path.join(__dirname, "..", "verdant.db"));

const products = [
  { pname: "Bringadi Intensive Hair Treatment Oil", netprice: 895, sellingprice: 1195, category: "Hair", severity: "High Severity", description: "Ayurvedic hair treatment oil for hair fall, scalp nourishment, and damaged hair care.", problem_tags: "hair-oil,hair-fall,scalp-care,dry-hair,damaged-hair", brand: "Kama Ayurveda", product_type: "Hair Oil" },
  { pname: "Bringadi Hair Cleanser", netprice: 625, sellingprice: 845, category: "Hair", severity: "Regular", description: "Gentle herbal shampoo for daily cleansing and scalp freshness.", problem_tags: "shampoo,hair-cleanser,scalp-care,daily-use", brand: "Kama Ayurveda", product_type: "Shampoo" },
  { pname: "Bringadi Hair Conditioner", netprice: 645, sellingprice: 875, category: "Hair", severity: "Improver", description: "Nourishing conditioner that helps soften hair and reduce dryness after shampooing.", problem_tags: "conditioner,dry-hair,frizz-control,soft-hair", brand: "Kama Ayurveda", product_type: "Conditioner" },
  { pname: "Sanobar Hair Cleanser", netprice: 595, sellingprice: 795, category: "Hair", severity: "Regular", description: "Natural hair cleanser for refreshing the scalp and maintaining clean hair.", problem_tags: "shampoo,hair-cleanser,scalp-care,daily-use", brand: "Kama Ayurveda", product_type: "Shampoo" },
  { pname: "Himalayan Deodar Hair Cleanser", netprice: 595, sellingprice: 795, category: "Hair", severity: "Regular", description: "Herbal shampoo for cleansing the scalp and supporting healthy-looking hair.", problem_tags: "shampoo,hair-cleanser,scalp-care,daily-use", brand: "Kama Ayurveda", product_type: "Shampoo" },
  { pname: "Rose & Jasmine Hair Conditioner", netprice: 625, sellingprice: 845, category: "Hair", severity: "Improver", description: "Floral hair conditioner for smoothness, softness, and frizz control.", problem_tags: "conditioner,dry-hair,frizz-control,soft-hair", brand: "Kama Ayurveda", product_type: "Conditioner" },
  { pname: "Organic Henna Powder", netprice: 345, sellingprice: 495, category: "Hair", severity: "Improver", description: "Natural henna powder for herbal hair coloring and hair conditioning.", problem_tags: "hair-color,henna,hair-treatment,conditioning", brand: "Kama Ayurveda", product_type: "Hair Color & Treatment" },
  { pname: "Organic Indigo Powder", netprice: 365, sellingprice: 525, category: "Hair", severity: "Improver", description: "Natural indigo powder used for herbal hair coloring and grey coverage routines.", problem_tags: "hair-color,indigo,grey-hair,hair-treatment", brand: "Kama Ayurveda", product_type: "Hair Color" },
  { pname: "Bhringraj Hair Vitalizer", netprice: 725, sellingprice: 995, category: "Hair", severity: "High Severity", description: "Hair vitalizer for weak roots, hair fall concerns, and scalp nourishment.", problem_tags: "hair-vitalizer,hair-fall,scalp-care,weak-roots", brand: "Forest Essentials", product_type: "Hair Tonic" },
  { pname: "Japapatti Hair Cleanser", netprice: 625, sellingprice: 845, category: "Hair", severity: "Regular", description: "Herbal shampoo for gentle cleansing and everyday hair freshness.", problem_tags: "shampoo,hair-cleanser,daily-use,scalp-care", brand: "Forest Essentials", product_type: "Shampoo" },
  { pname: "Bhringraj & Shikakai Hair Cleanser", netprice: 645, sellingprice: 875, category: "Hair", severity: "High Severity", description: "Bhringraj and shikakai shampoo for scalp cleansing and hair fall control routines.", problem_tags: "shampoo,hair-fall,shikakai,bhringraj,scalp-care", brand: "Forest Essentials", product_type: "Shampoo" },
  { pname: "Japapatti Hair Conditioner", netprice: 645, sellingprice: 875, category: "Hair", severity: "Improver", description: "Conditioner for improving softness, manageability, and dry hair texture.", problem_tags: "conditioner,dry-hair,frizz-control,soft-hair", brand: "Forest Essentials", product_type: "Conditioner" },
  { pname: "Intensive Hair Repair Masque Japapatti & Brahmi", netprice: 895, sellingprice: 1195, category: "Hair", severity: "High Severity", description: "Deep repair hair mask for damaged, dry, and stressed hair.", problem_tags: "hair-mask,damaged-hair,dry-hair,hair-repair,deep-conditioning", brand: "Forest Essentials", product_type: "Hair Mask" },
  { pname: "Hair Thickening Spray Bhringraj & Shikakai", netprice: 775, sellingprice: 1045, category: "Hair", severity: "Improver", description: "Hair thickening spray for volume, weak hair, and fuller-looking strands.", problem_tags: "hair-spray,hair-volume,thin-hair,weak-hair", brand: "Forest Essentials", product_type: "Hair Spray" },
  { pname: "Bio Kelp Protein Shampoo", netprice: 225, sellingprice: 325, category: "Hair", severity: "High Severity", description: "Protein shampoo for weak hair, hair fall concerns, and scalp cleansing.", problem_tags: "shampoo,hair-fall,protein-shampoo,weak-hair", brand: "Biotique", product_type: "Shampoo" },
  { pname: "Bio Green Apple Shampoo", netprice: 215, sellingprice: 299, category: "Hair", severity: "Regular", description: "Fresh cleansing shampoo for normal hair and everyday use.", problem_tags: "shampoo,daily-use,hair-cleanser,normal-hair", brand: "Biotique", product_type: "Shampoo" },
  { pname: "Bio Soya Protein Shampoo", netprice: 225, sellingprice: 325, category: "Hair", severity: "Improver", description: "Protein-rich shampoo for dry, dull, and weak hair.", problem_tags: "shampoo,protein-shampoo,dry-hair,dull-hair,weak-hair", brand: "Biotique", product_type: "Shampoo" },
  { pname: "Bio Bhringraj Therapeutic Hair Oil", netprice: 235, sellingprice: 349, category: "Hair", severity: "High Severity", description: "Therapeutic hair oil for hair fall, scalp nourishment, and stronger roots.", problem_tags: "hair-oil,hair-fall,bhringraj,scalp-care,weak-roots", brand: "Biotique", product_type: "Hair Oil" },
  { pname: "Bio Mountain Ebony Hair Serum", netprice: 245, sellingprice: 365, category: "Hair", severity: "Improver", description: "Hair serum for dull hair, frizz control, and smoother-looking strands.", problem_tags: "hair-serum,frizz-control,dull-hair,smooth-hair", brand: "Biotique", product_type: "Serum" },
  { pname: "Bio Thyme Volume Conditioner", netprice: 225, sellingprice: 325, category: "Hair", severity: "Improver", description: "Volumizing conditioner for limp hair and improved manageability.", problem_tags: "conditioner,hair-volume,thin-hair,soft-hair", brand: "Biotique", product_type: "Conditioner" },
  { pname: "Bio Henna Leaf Fresh Texture Shampoo", netprice: 215, sellingprice: 315, category: "Hair", severity: "Regular", description: "Henna-based shampoo for cleansing and improving hair texture.", problem_tags: "shampoo,henna,hair-texture,daily-use", brand: "Biotique", product_type: "Shampoo" },
  { pname: "Onion Hair Oil", netprice: 295, sellingprice: 449, category: "Hair", severity: "High Severity", description: "Onion hair oil for hair fall control, root strength, and scalp nourishment.", problem_tags: "hair-oil,onion-oil,hair-fall,weak-roots,scalp-care", brand: "Mamaearth", product_type: "Hair Oil" },
  { pname: "Onion Shampoo", netprice: 275, sellingprice: 399, category: "Hair", severity: "High Severity", description: "Onion shampoo for hair fall concerns and gentle scalp cleansing.", problem_tags: "shampoo,onion-shampoo,hair-fall,scalp-care", brand: "Mamaearth", product_type: "Shampoo" },
  { pname: "Onion Conditioner", netprice: 275, sellingprice: 399, category: "Hair", severity: "Improver", description: "Conditioner for softening hair and supporting hair fall care routines.", problem_tags: "conditioner,onion-conditioner,hair-fall,dry-hair,frizz-control", brand: "Mamaearth", product_type: "Conditioner" },
  { pname: "Tea Tree Shampoo", netprice: 295, sellingprice: 429, category: "Hair", severity: "High Severity", description: "Tea tree anti-dandruff shampoo for itchy scalp and dandruff control.", problem_tags: "shampoo,anti-dandruff,dandruff,itchy-scalp,tea-tree", brand: "Mamaearth", product_type: "Anti-Dandruff Shampoo" },
  { pname: "BhringAmla Hair Oil", netprice: 295, sellingprice: 449, category: "Hair", severity: "High Severity", description: "Bhringraj and amla hair oil for hair fall, nourishment, and root strength.", problem_tags: "hair-oil,hair-fall,bhringraj,amla,weak-roots", brand: "Mamaearth", product_type: "Hair Oil" },
  { pname: "Rosemary Hair Growth Oil", netprice: 325, sellingprice: 499, category: "Hair", severity: "High Severity", description: "Rosemary hair oil for hair growth support, scalp care, and weak roots.", problem_tags: "hair-oil,hair-growth,hair-fall,rosemary,scalp-care", brand: "Mamaearth", product_type: "Hair Oil" },
  { pname: "Apple Cider Vinegar Shampoo", netprice: 345, sellingprice: 499, category: "Hair", severity: "Improver", description: "Apple cider vinegar shampoo for scalp buildup, shine, and cleansing.", problem_tags: "shampoo,scalp-buildup,dull-hair,shine,apple-cider-vinegar", brand: "WOW Skin Science", product_type: "Shampoo" },
  { pname: "Onion Black Seed Hair Oil", netprice: 375, sellingprice: 549, category: "Hair", severity: "High Severity", description: "Onion and black seed hair oil for hair fall control and scalp nourishment.", problem_tags: "hair-oil,onion-oil,hair-fall,black-seed,scalp-care", brand: "WOW Skin Science", product_type: "Hair Oil" },
  { pname: "Coconut Milk Shampoo", netprice: 345, sellingprice: 499, category: "Hair", severity: "Improver", description: "Moisturizing coconut milk shampoo for dry and rough hair.", problem_tags: "shampoo,dry-hair,moisturizing,coconut-milk,rough-hair", brand: "WOW Skin Science", product_type: "Shampoo" },
  { pname: "Moroccan Argan Oil Shampoo", netprice: 375, sellingprice: 549, category: "Hair", severity: "Improver", description: "Argan oil shampoo for frizz control, shine, and dry hair care.", problem_tags: "shampoo,argan-oil,frizz-control,dry-hair,shine", brand: "WOW Skin Science", product_type: "Shampoo" },
  { pname: "Red Onion Black Seed Oil Shampoo", netprice: 375, sellingprice: 549, category: "Hair", severity: "High Severity", description: "Red onion and black seed shampoo for hair fall and scalp care.", problem_tags: "shampoo,onion-shampoo,hair-fall,black-seed,scalp-care", brand: "WOW Skin Science", product_type: "Shampoo" },
  { pname: "Himalayan Rose Conditioner", netprice: 345, sellingprice: 499, category: "Hair", severity: "Improver", description: "Conditioner for soft, smooth, and manageable hair.", problem_tags: "conditioner,dry-hair,frizz-control,soft-hair", brand: "WOW Skin Science", product_type: "Conditioner" },
  { pname: "Amla & Bhringraj Shampoo", netprice: 245, sellingprice: 349, category: "Hair", severity: "High Severity", description: "Amla and bhringraj shampoo for hair fall care and scalp cleansing.", problem_tags: "shampoo,hair-fall,amla,bhringraj,scalp-care", brand: "Khadi Natural", product_type: "Shampoo" },
  { pname: "Neem & Aloe Vera Shampoo", netprice: 235, sellingprice: 335, category: "Hair", severity: "Regular", description: "Neem and aloe vera shampoo for clean scalp and daily hair care.", problem_tags: "shampoo,neem,aloe-vera,scalp-care,daily-use", brand: "Khadi Natural", product_type: "Shampoo" },
  { pname: "Shikakai & Honey Shampoo", netprice: 245, sellingprice: 349, category: "Hair", severity: "Improver", description: "Shikakai and honey shampoo for gentle cleansing and dry hair softness.", problem_tags: "shampoo,shikakai,honey,dry-hair,soft-hair", brand: "Khadi Natural", product_type: "Shampoo" },
  { pname: "Herbal Hair Conditioner", netprice: 235, sellingprice: 335, category: "Hair", severity: "Improver", description: "Herbal conditioner for smoother, softer, and manageable hair.", problem_tags: "conditioner,herbal-conditioner,dry-hair,frizz-control", brand: "Khadi Natural", product_type: "Conditioner" },
  { pname: "Bhringraj Hair Oil", netprice: 225, sellingprice: 325, category: "Hair", severity: "High Severity", description: "Bhringraj hair oil for hair fall control and scalp nourishment.", problem_tags: "hair-oil,bhringraj,hair-fall,scalp-care,weak-roots", brand: "Khadi Natural", product_type: "Hair Oil" },
  { pname: "Amla Hair Oil", netprice: 215, sellingprice: 315, category: "Hair", severity: "Improver", description: "Amla hair oil for nourishment, shine, and stronger-looking hair.", problem_tags: "hair-oil,amla,dull-hair,shine,weak-hair", brand: "Khadi Natural", product_type: "Hair Oil" },
  { pname: "Kesh Kanti Natural Hair Cleanser", netprice: 95, sellingprice: 150, category: "Hair", severity: "Regular", description: "Natural hair cleanser for regular scalp and hair cleansing.", problem_tags: "shampoo,hair-cleanser,daily-use,scalp-care", brand: "Patanjali", product_type: "Shampoo" },
  { pname: "Kesh Kanti Aloe Vera Hair Cleanser", netprice: 105, sellingprice: 160, category: "Hair", severity: "Regular", description: "Aloe vera hair cleanser for gentle cleaning and dry scalp comfort.", problem_tags: "shampoo,aloe-vera,dry-scalp,hair-cleanser,daily-use", brand: "Patanjali", product_type: "Shampoo" },
  { pname: "Kesh Kanti Milk Protein Hair Cleanser", netprice: 105, sellingprice: 160, category: "Hair", severity: "Improver", description: "Milk protein hair cleanser for dry, dull, and weak hair.", problem_tags: "shampoo,protein-shampoo,dry-hair,dull-hair,weak-hair", brand: "Patanjali", product_type: "Shampoo" },
  { pname: "Kesh Kanti Anti-Dandruff Hair Cleanser", netprice: 115, sellingprice: 175, category: "Hair", severity: "High Severity", description: "Anti-dandruff hair cleanser for flaky scalp and dandruff control.", problem_tags: "shampoo,anti-dandruff,dandruff,flaky-scalp,itchy-scalp", brand: "Patanjali", product_type: "Shampoo" },
  { pname: "Kesh Kanti Hair Oil", netprice: 115, sellingprice: 180, category: "Hair", severity: "Regular", description: "Hair oil for regular nourishment and scalp massage.", problem_tags: "hair-oil,scalp-care,daily-use,hair-nourishment", brand: "Patanjali", product_type: "Hair Oil" },
  { pname: "Aloe Vera Juice Shampoo", netprice: 295, sellingprice: 449, category: "Hair", severity: "Regular", description: "Aloe vera shampoo for gentle cleansing and dry hair care.", problem_tags: "shampoo,aloe-vera,dry-hair,hair-cleanser,daily-use", brand: "Organic Harvest", product_type: "Shampoo" },
  { pname: "Organic Harvest Anti-Dandruff Shampoo", netprice: 325, sellingprice: 475, category: "Hair", severity: "High Severity", description: "Anti-dandruff shampoo for flaky scalp, dandruff, and scalp cleansing.", problem_tags: "shampoo,anti-dandruff,dandruff,flaky-scalp,scalp-care", brand: "Organic Harvest", product_type: "Shampoo" },
  { pname: "Organic Harvest Hair Conditioner", netprice: 325, sellingprice: 475, category: "Hair", severity: "Improver", description: "Hair conditioner for softness, smoothness, and frizz control.", problem_tags: "conditioner,dry-hair,frizz-control,soft-hair", brand: "Organic Harvest", product_type: "Conditioner" },
  { pname: "Bhringraj & Onion Hair Oil", netprice: 425, sellingprice: 625, category: "Hair", severity: "High Severity", description: "Bhringraj and onion hair oil for hair fall, scalp care, and root strength.", problem_tags: "hair-oil,hair-fall,bhringraj,onion-oil,weak-roots", brand: "Just Herbs", product_type: "Hair Oil" },
  { pname: "Castor & Black Onion Seed Hair Oil", netprice: 545, sellingprice: 795, category: "Hair", severity: "High Severity", description: "Castor and black onion seed hair oil for hair fall control and nourishment.", problem_tags: "hair-oil,hair-fall,castor-oil,onion-oil,scalp-care", brand: "Juicy Chemistry", product_type: "Hair Oil" },
  { pname: "Hibiscus & Onion Hair Oil", netprice: 445, sellingprice: 675, category: "Hair", severity: "High Severity", description: "Hibiscus and onion hair oil for hair fall, weak roots, and scalp nourishment.", problem_tags: "hair-oil,hair-fall,hibiscus,onion-oil,weak-roots", brand: "SoulTree", product_type: "Hair Oil" },
];

const insert = db.prepare(`
  INSERT INTO products (pname, netprice, sellingprice, category, severity, description, image, problem_tags, brand, product_type)
  VALUES (@pname, @netprice, @sellingprice, @category, @severity, @description, '', @problem_tags, @brand, @product_type)
`);

const skipExisting = db.prepare("SELECT 1 FROM products WHERE pname = ?");

const tx = db.transaction((rows) => {
  let inserted = 0, skipped = 0;
  for (const r of rows) {
    if (skipExisting.get(r.pname)) { skipped++; continue; }
    insert.run(r);
    inserted++;
  }
  return { inserted, skipped };
});

const result = tx(products);
console.log(`Inserted ${result.inserted}, skipped ${result.skipped} (already existed).`);
console.log(`Total products now: ${db.prepare("SELECT COUNT(*) c FROM products").get().c}`);
